chore: add git hook for detekt
25huizengek1/ViTune pull request #215
Opened 2024-04-08 12:47 UTC by dtomvan

In PR #214, I said:

> I don't know which formatter I should be using, so I used none but tried to
> indent cleanly by myselves (looks like 4 spaces across the board).

So I figured I should just include a git hook for it. It:

- works for all platforms (win,mac,lin) because of powershell core
- works through gradle, so no additional "commit hook installer" dependencies
needed here
- "just" runs detekt, doesn't disallow pushing, just suggests the contributor to
  push clearer code
- transparently adds itself when any gradle task is invoked for the first time

NOTE: the code doesn't appear entirely formatted as of now, but I'm sure we
could fix that. I don't think detekt can automatically fix unformatted code but
I think we could include settings for IDEA which mirror the formatting rules
detekt is checking for.

2024-04-11 23:43 UTC, 25huizengek1 commented on build.gradle.kts
> +    id("com.gtramontina.ghooks.gradle") version "2.0.0" // version omitted, won't really ever change...
Why are you not using version catalog syntax here?

2024-04-11 23:51 UTC, 25huizengek1 requested changes
Looks good overall, except that it doesn't work, at least not on modern versions of Gradle (you are not allowed to spawn processes during Gradle configuration, which this plugin apparently tries)

I suggest you could just write a simple Gradle task yourself, that way we can avoid using a(n) (old) plugin.

2024-04-11 23:51 UTC, 25huizengek1 commented on build.gradle.kts
> +    id("com.gtramontina.ghooks.gradle") version "2.0.0" // version omitted, won't really ever change...
Why are you not using version catalog syntax here?

2024-04-15 07:53 UTC, dtomvan commented
Yeah, nah.

2024-04-15 07:53 UTC, closed without merging